# Generated by Django 3.2.23 on 2023-12-25 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0002_userprofile_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoxingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=255)),
            ],
        ),
    ]
