# Generated by Django 3.2.23 on 2024-01-17 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0004_auto_20240117_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='draws',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='losses',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='wins',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
