# Generated by Django 3.2.23 on 2024-01-17 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0005_auto_20240117_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='draws',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='losses',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='wins',
            field=models.IntegerField(default=0),
        ),
    ]
