# Generated by Django 3.2.23 on 2024-01-21 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0007_auto_20240121_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='boxingevent',
            name='title',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
