# Generated by Django 3.2.23 on 2024-01-28 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0008_boxingevent_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventregistration',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventregistration',
            name='user',
        ),
        migrations.RemoveField(
            model_name='fight',
            name='blue_boxer',
        ),
        migrations.RemoveField(
            model_name='fight',
            name='red_boxer',
        ),
        migrations.RemoveField(
            model_name='boxingevent',
            name='fights',
        ),
        migrations.RemoveField(
            model_name='boxingevent',
            name='registered_users',
        ),
        migrations.DeleteModel(
            name='EventFight',
        ),
        migrations.DeleteModel(
            name='EventRegistration',
        ),
        migrations.DeleteModel(
            name='Fight',
        ),
    ]
