# Generated by Django 3.2.23 on 2024-01-28 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0009_auto_20240128_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='boxingevent',
            name='fights_count',
            field=models.IntegerField(default=0),
        ),
    ]
