# Generated by Django 3.2.23 on 2024-01-28 23:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('box', '0010_boxingevent_fights_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boxingevent',
            name='fights_count',
        ),
        migrations.CreateModel(
            name='Fight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blue_boxer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blue_boxer', to=settings.AUTH_USER_MODEL)),
                ('red_boxer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='red_boxer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='box.boxingevent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventFight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='box.boxingevent')),
                ('fight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='box.fight')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('event', 'order')},
            },
        ),
        migrations.AddField(
            model_name='boxingevent',
            name='fights',
            field=models.ManyToManyField(through='box.EventFight', to='box.Fight'),
        ),
        migrations.AddField(
            model_name='boxingevent',
            name='registered_users',
            field=models.ManyToManyField(through='box.EventRegistration', to=settings.AUTH_USER_MODEL),
        ),
    ]
