# Generated by Django 3.2.23 on 2024-01-28 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0011_auto_20240128_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fight',
            name='blue_boxer',
        ),
        migrations.RemoveField(
            model_name='fight',
            name='red_boxer',
        ),
        migrations.RemoveField(
            model_name='boxingevent',
            name='fights',
        ),
        migrations.RemoveField(
            model_name='boxingevent',
            name='registered_users',
        ),
        migrations.RemoveField(
            model_name='eventregistration',
            name='user',
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='opponent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opponent_registrations', to='box.userprofile'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='user_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='box.userprofile'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='box.boxingevent'),
        ),
        migrations.DeleteModel(
            name='EventFight',
        ),
        migrations.DeleteModel(
            name='Fight',
        ),
    ]
