# Generated by Django 3.2.23 on 2024-01-28 23:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('box', '0012_auto_20240128_2334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventregistration',
            name='opponent',
        ),
        migrations.RemoveField(
            model_name='eventregistration',
            name='user_profile',
        ),
        migrations.AddField(
            model_name='boxingevent',
            name='registered_users',
            field=models.ManyToManyField(through='box.EventRegistration', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='box.boxingevent'),
        ),
        migrations.CreateModel(
            name='Fight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blue_boxer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blue_boxer', to=settings.AUTH_USER_MODEL)),
                ('red_boxer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='red_boxer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventFight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='box.boxingevent')),
                ('fight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='box.fight')),
            ],
        ),
        migrations.AddField(
            model_name='boxingevent',
            name='fights',
            field=models.ManyToManyField(through='box.EventFight', to='box.Fight'),
        ),
    ]
