# Generated by Django 3.2.23 on 2024-01-29 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0013_auto_20240128_2359'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventfight',
            options={'ordering': ['order']},
        ),
        migrations.AlterUniqueTogether(
            name='eventfight',
            unique_together={('event', 'order')},
        ),
    ]
