# Generated by Django 3.2.23 on 2024-02-03 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0015_eventregistration_matched'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventfight',
            name='blue_boxer_result',
            field=models.CharField(blank=True, choices=[('win', 'Win'), ('loss', 'Loss'), ('draw', 'Draw')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='eventfight',
            name='red_boxer_result',
            field=models.CharField(blank=True, choices=[('win', 'Win'), ('loss', 'Loss'), ('draw', 'Draw')], max_length=10, null=True),
        ),
    ]
