# Generated by Django 3.2.23 on 2024-02-06 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0016_auto_20240203_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='not_matched_counter',
            field=models.IntegerField(default=0),
        ),
    ]
