# Generated by Django 3.2.23 on 2024-02-10 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0018_alter_userprofile_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventregistration',
            name='not_matched_counter',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='not_matched_counter',
            field=models.IntegerField(default=0),
        ),
    ]
