# Generated by Django 3.2.23 on 2024-02-10 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0019_auto_20240210_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='registered',
            field=models.BooleanField(default=False),
        ),
    ]
