# Generated by Django 3.2.23 on 2024-02-16 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0020_eventregistration_registered'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventfight',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='eventfight',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='eventfight',
            name='order',
        ),
    ]
