# Generated by Django 3.2.23 on 2024-02-16 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0021_auto_20240216_0628'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventfight',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='eventfight',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='eventfight',
            unique_together={('event', 'order')},
        ),
    ]
