# Generated by Django 3.2.23 on 2024-03-07 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0022_auto_20240216_0631'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='boxer_type',
            field=models.CharField(choices=[('amateur', 'Amateur'), ('professional', 'Professional')], default='amateur', max_length=20),
        ),
    ]
